import { strip } from '../../utils'

const ProductCard = React.forwardRef(({item}, ref) => {
    return (
        <div>
            <h2>{item.name}</h2>
            <p >
            {strip(item.description)} 
            </p>
        </div>
    )
})

export default ProductCard


// {
//     id: 1008,
//     name: 'Crema de Maní - Coco',
//     slug: 'crema-de-mani-coco',
//     permalink: 'https://hardy.fit/producto/crema-de-mani-coco/',
//     date_created: '2020-04-05T23:33:35',
//     date_created_gmt: '2020-04-06T02:33:35',
//     date_modified: '2020-04-05T23:33:46',
//     date_modified_gmt: '2020-04-06T02:33:46',
//     type: 'simple',
//     status: 'publish',
//     featured: false,
//     catalog_visibility: 'visible',
//     description: '<p><img class="alignnone size-medium wp-image-411" src="https://hardy.fit/wp-content/uploads/2017/12/pote_coco-300x288.png" alt="hardy coco" width="300" height="288" />Crema de maní con rayadura de coco</p>\n',
//     short_description: '<p>Este producto es sublime</p>\n',
//     sku: '34566543',
//     price: '345',
//     regular_price: '350',
//     sale_price: '345',
//     date_on_sale_from: null,
//     date_on_sale_from_gmt: null,
//     date_on_sale_to: null,
//     date_on_sale_to_gmt: null,
//     price_html: '<del><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>350.00</span></del> <ins><span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>345.00</span></ins>',
//     on_sale: true,
//     purchasable: true,
//     total_sales: 0,
//     virtual: false,
//     downloadable: false,
//     downloads: [],
//     download_limit: -1,
//     download_expiry: -1,
//     external_url: '',
//     button_text: '',
//     tax_status: 'taxable',
//     tax_class: '',
//     manage_stock: true,
//     stock_quantity: 100,
//     stock_status: 'instock',
//     backorders: 'yes',
//     backorders_allowed: true,
//     backordered: false,
//     sold_individually: false,
//     weight: '778',
//     dimensions: { length: '112', width: '22', height: '44' },
//     shipping_required: true,
//     shipping_taxable: true,
//     shipping_class: '',
//     shipping_class_id: 0,
//     reviews_allowed: true,
//     average_rating: '0.00',
//     rating_count: 0,
//     related_ids: [],
//     upsell_ids: [ 1005 ],
//     cross_sell_ids: [ 1005 ],
//     parent_id: 0,
//     purchase_note: '<p>Gracias por su compra</p>\n',
//     categories: [ [Object] ],
//     tags: [ [Object], [Object], [Object], [Object], [Object] ],
//     images: [ [Object], [Object], [Object] ],
//     attributes: [],
//     default_attributes: [],
//     variations: [],
//     grouped_products: [],
//     menu_order: 0,
//     meta_data: [ [Object], [Object] ],
//     _links: { self: [Array], collection: [Array] }
//   },
//   {
//     id: 1005,
//     name: 'Hardy Natural',
//     slug: 'hardy-natural',
//     permalink: 'https://hardy.fit/producto/hardy-natural/',
//     date_created: '2020-03-15T23:52:18',
//     date_created_gmt: '2020-03-16T02:52:18',
//     date_modified: '2020-03-19T00:06:26',
//     date_modified_gmt: '2020-03-19T03:06:26',
//     type: 'simple',
//     status: 'publish',
//     featured: false,
//     catalog_visibility: 'visible',
//     description: '<p>Alta crema de mani my coronafriend!</p>\n',
//     short_description: '<p>surplus!</p>\n',
//     sku: '',
//     price: '3400',
//     regular_price: '3400',
//     sale_price: '',
//     date_on_sale_from: null,
//     date_on_sale_from_gmt: null,
//     date_on_sale_to: null,
//     date_on_sale_to_gmt: null,
//     price_html: '<span class="woocommerce-Price-amount amount"><span class="woocommerce-Price-currencySymbol">&#36;</span>3,400.00</span>',
//     on_sale: false,
//     purchasable: true,
//     total_sales: 0,
//     virtual: false,
//     downloadable: false,
//     downloads: [],
//     download_limit: -1,
//     download_expiry: -1,
//     external_url: '',
//     button_text: '',
//     tax_status: 'taxable',
//     tax_class: '',
//     manage_stock: false,
//     stock_quantity: null,
//     stock_status: 'instock',
//     backorders: 'no',
//     backorders_allowed: false,
//     backordered: false,
//     sold_individually: false,
//     weight: '',
//     dimensions: { length: '', width: '', height: '' },
//     shipping_required: true,
//     shipping_taxable: true,
//     shipping_class: '',
//     shipping_class_id: 0,
//     reviews_allowed: true,
//     average_rating: '0.00',
//     rating_count: 0,
//     related_ids: [],
//     upsell_ids: [],
//     cross_sell_ids: [],
//     parent_id: 0,
//     purchase_note: '',
//     categories: [ [Object] ],
//     tags: [],
//     images: [],
//     attributes: [],
//     default_attributes: [],
//     variations: [],
//     grouped_products: [],
//     menu_order: 0,
//     meta_data: [ [Object], [Object] ],
//     _links: { self: [Array], collection: [Array] }
//   }